version: "3.8"

services:
  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: true
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_PASSWORD}
      INFLUXDB_DB: ${INFLUXDB_NAME}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    command: ["/bin/sh", "-c", "/init-influxdb.sh && exit 0"]
    restart: "no"
networks:
  cozie-network:
