version: "3.8"

services:
  influxdb:
    image: influxdb:1.8.10-alpine # Use a Fixed influxDB version.
    container_name: influxdb
    # Uncomment for development
    ports:
      - "8086:8086" # Expose InfluxDB on localhost:8086 for local access
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: Aalto
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_NAME}
      #INFLUXDB_ADMIN_USER: ${INFLUXDB_USER} # Admin username
      #INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_PASSWORD} # Admin password
      #INFLUXDB_HTTP_AUTH_ENABLED: "true" # Enable HTTP authentication
    volumes:
      - ${INFLUXDB_FOLDER}/db:/var/lib/influxdb2 # Persist data
      - ${INFLUXDB_FOLDER}/config:/etc/influxdb2 # Persist data
    networks:
      - cozie-network
  redis:
    image: "redis:alpine"
    networks:
      - cozie-network
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CERTIFICATE_FOLDER}:/ssl
    depends_on:
      - cozie-app
    networks:
      - cozie-network
  celery_worker:
    build:
      context: ./queue_broker
    environment:
      INFLUXDB_NAME: ${INFLUXDB_NAME}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    depends_on:
      - redis
    networks:
      - cozie-network
  cozie-app:
    build:
      context: ./fastapi_server
    environment:
      DOWNLOAD_FOLDER: /downloads
      INFLUXDB_NAME: ${INFLUXDB_NAME}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      ONESIGNAL_TOKEN: ${ONESIGNAL_TOKEN}
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}
      USER_WRITE_KEY: ${USER_WRITE_KEY}
      USER_READ_KEY: ${USER_READ_KEY}
      RESEARCHER_KEY: ${RESEARCHER_KEY}
    networks:
      - cozie-network
    depends_on:
      - influxdb
      - celery_worker
    volumes:
      # Mount host folder for the downloads into the container.
      - ${DOWNLOAD_FOLDER}:/downloads
networks:
  cozie-network:
